# Usa una imagen base de Node.js
FROM node:lts-alpine

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia solo los archivos de dependencias primero
COPY package*.json ./

# Instala las dependencias y limpia la caché de npm
RUN npm install && npm cache clean --force

# Copia el resto de los archivos de la aplicación
COPY . .

# Expone el puerto en el que correrá el servidor
EXPOSE 5173

# Comando para iniciar el servidor
ENTRYPOINT ["npm", "run", "dev"]






