# Usa una imagen base de Node.js
FROM node:lts-alpine

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia solo los archivos de dependencias primero
COPY package*.json ./

# Instala las dependencias y nodemon en un solo paso
RUN npm install && npm install -g nodemon && npm cache clean --force

# Copia el resto de los archivos de la aplicación
COPY . .

# Expone el puerto en el que correrá el servidor
EXPOSE 3000

# Comando para iniciar el servidor
ENTRYPOINT ["nodemon", "src/server.js"]

